/**
 * emulator-loader.ts — owns the BasiliskII boot lifecycle.
 *
 * Renders into the `#emulator-canvas-mount` slot inside the marketer's
 * "Macintosh" window chrome (see main.ts). Owns:
 *   - period-styled progress UI ("Loading BasiliskII… 1.7 MB")
 *   - canvas creation
 *   - WASM core fetch + instantiation (planned)
 *   - boot disk + app.dsk mount (planned)
 *
 * ─── Current status ──────────────────────────────────────────────────────
 *
 * The BasiliskII WASM artifacts ARE wired (fetch-emulator.sh pulls them
 * into /emulator/ and we fetch them here). But Infinite Mac's emulator
 * doesn't boot from a single .dsk; it consumes a chunked-disk JSON
 * manifest that's generated by their build pipeline and served from a
 * private R2 bucket. We have no public boot disk source for System 7.5.5,
 * so the loader currently runs through the visible "downloading core"
 * phase (real bytes!), then enters STUB_MODE and renders a message
 * inside the canvas mount instead of trying to start a boot it can't
 * complete. See LEARNINGS.md (2026-05-08, "boot disk plumbing") and
 * `EmulatorConfig.bootDiskUrl` for the resolution path.
 *
 * Once that's unblocked, the actual boot path is roughly:
 *
 *   1. Fetch boot disk manifest JSON, pin chunks ahead of cursor.
 *   2. Build an `EmulatorWorkerConfig` (see Infinite Mac
 *      src/emulator/common/common.ts, EmulatorWorkerConfig type).
 *   3. Spawn the BasiliskII Emscripten Module with `arguments` pointing
 *      at the prefs file (rendered from BasiliskIIPrefs.txt + our disks).
 *   4. The .js loader auto-loads /emulator/BasiliskII.wasm sibling.
 *   5. Wire input events (see emulator-input.ts) into the shared input
 *      buffer at the addresses defined in InputBufferAddresses.
 *
 * Reference paths in upstream (mihaip/infinite-mac, pinned in
 * scripts/fetch-emulator.sh):
 *   src/emulator/worker/worker.ts          -- boot orchestration
 *   src/emulator/worker/emulators.ts       -- prefs + disk wiring
 *   src/emulator/common/common.ts          -- shared types + chunk URL
 *   src/emulator/ui/config.ts              -- configToMacemuPrefs()
 */

import type { EmulatorConfig } from "./emulator-config";
import { wireInput } from "./emulator-input";

type LoaderPhase =
  | { kind: "idle" }
  | { kind: "fetching"; label: string; loadedBytes: number; totalBytes: number }
  | { kind: "starting" }
  | { kind: "running" }
  | { kind: "stub"; reason: string }
  | { kind: "error"; message: string };

interface LoaderHandles {
  mount: HTMLElement;
  /** Replaces mount contents wholesale and re-binds DOM refs. */
  setPhase(phase: LoaderPhase): void;
}

/** Public entry point. Returns an abort-able handle. */
export function startEmulator(
  config: EmulatorConfig,
  mount: HTMLElement,
): { dispose(): void } {
  const handles = renderShell(mount);
  const ac = new AbortController();

  void boot(config, handles, ac.signal).catch((err) => {
    console.error("[emulator] boot failed:", err);
    handles.setPhase({
      kind: "error",
      message: err instanceof Error ? err.message : String(err),
    });
  });

  return {
    dispose: () => ac.abort(),
  };
}

// ── Boot sequence ─────────────────────────────────────────────────────

async function boot(
  config: EmulatorConfig,
  handles: LoaderHandles,
  signal: AbortSignal,
): Promise<void> {
  // Phase 1: pull the BasiliskII core. Real bytes; we surface progress.
  await fetchWithProgress(config.coreUrl, "Loading BasiliskII…", handles, signal);
  await fetchWithProgress(config.wasmUrl, "Loading WebAssembly core…", handles, signal);

  // Phase 2: app disk. Optional — only fetch if we'd actually use it
  // (i.e. only once boot disk is wired). For now we still HEAD-check it
  // so failures show up early, but tolerate 404 (CI may not have built it
  // for a fresh fork yet).
  try {
    const r = await fetch(config.appDiskUrl, { method: "HEAD", signal });
    if (!r.ok && r.status !== 404) {
      console.warn("[emulator] app.dsk HEAD returned", r.status);
    }
  } catch (err) {
    if ((err as Error).name !== "AbortError") {
      console.warn("[emulator] app.dsk HEAD failed:", err);
    }
  }

  // Phase 3: boot. Currently always falls into STUB because bootDiskUrl is
  // null — see LEARNINGS.md and emulator-config.ts for the unblock plan.
  if (!config.bootDiskUrl) {
    handles.setPhase({
      kind: "stub",
      reason:
        "System 7.5.5 boot disk source is not yet wired. The emulator core " +
        "downloaded successfully (look at the network tab) but Infinite Mac's " +
        "chunked-disk manifest URL pattern is not public — see LEARNINGS.md.",
    });
    return;
  }

  // Once unblocked, this is where the real init lives. Placeholder so the
  // shape is visible to the next agent picking it up:
  handles.setPhase({ kind: "starting" });
  const canvas = mountCanvas(handles.mount, config.screen);
  // TODO: instantiate the BasiliskII Emscripten Module with arguments built
  // from BasiliskIIPrefs.txt + our disk specs, hand it the canvas, attach
  // input wiring.
  wireInput(canvas);
  handles.setPhase({ kind: "running" });
}

// ── Networking with progress ──────────────────────────────────────────

async function fetchWithProgress(
  url: string,
  label: string,
  handles: LoaderHandles,
  signal: AbortSignal,
): Promise<ArrayBuffer> {
  handles.setPhase({ kind: "fetching", label, loadedBytes: 0, totalBytes: 0 });

  const res = await fetch(url, { signal });
  if (!res.ok) {
    throw new Error(`${label} HTTP ${res.status}`);
  }

  const totalHeader = res.headers.get("content-length");
  const totalBytes = totalHeader ? parseInt(totalHeader, 10) : 0;

  if (!res.body) {
    // Old browser fallback — no streaming progress.
    const buf = await res.arrayBuffer();
    handles.setPhase({
      kind: "fetching",
      label,
      loadedBytes: buf.byteLength,
      totalBytes: buf.byteLength,
    });
    return buf;
  }

  const reader = res.body.getReader();
  const chunks: Uint8Array[] = [];
  let loaded = 0;

  for (;;) {
    const { value, done } = await reader.read();
    if (done) break;
    if (value) {
      chunks.push(value);
      loaded += value.byteLength;
      handles.setPhase({
        kind: "fetching",
        label,
        loadedBytes: loaded,
        totalBytes,
      });
    }
  }

  // Concatenate.
  const out = new Uint8Array(loaded);
  let offset = 0;
  for (const c of chunks) {
    out.set(c, offset);
    offset += c.byteLength;
  }
  return out.buffer;
}

// ── DOM ──────────────────────────────────────────────────────────────

function renderShell(mount: HTMLElement): LoaderHandles {
  const setPhase = (phase: LoaderPhase) => {
    mount.innerHTML = renderPhase(phase);
  };
  setPhase({ kind: "idle" });
  return { mount, setPhase };
}

function mountCanvas(
  mount: HTMLElement,
  screen: { width: number; height: number },
): HTMLCanvasElement {
  mount.innerHTML = "";
  const canvas = document.createElement("canvas");
  canvas.id = "emulator-canvas";
  canvas.width = screen.width;
  canvas.height = screen.height;
  canvas.className = "emulator-canvas";
  // Tabindex so the canvas can receive keyboard focus.
  canvas.tabIndex = 0;
  mount.appendChild(canvas);
  return canvas;
}

function renderPhase(phase: LoaderPhase): string {
  switch (phase.kind) {
    case "idle":
      return progressBlock("Initializing…", 0, 0);
    case "fetching": {
      return progressBlock(phase.label, phase.loadedBytes, phase.totalBytes);
    }
    case "starting":
      return progressBlock("Starting Macintosh…", 1, 1);
    case "running":
      // Canvas takes over; this branch isn't normally rendered (mountCanvas
      // wipes the mount), but we keep it for completeness.
      return "";
    case "stub":
      return stubBlock(phase.reason);
    case "error":
      return errorBlock(phase.message);
  }
}

function progressBlock(label: string, loaded: number, total: number): string {
  const pct =
    total > 0 ? Math.min(100, Math.round((loaded / total) * 100)) : 0;
  const counter =
    total > 0
      ? `${formatBytes(loaded)} / ${formatBytes(total)}`
      : loaded > 0
        ? formatBytes(loaded)
        : "";
  return /* html */ `
    <div class="loader" role="status" aria-live="polite">
      <div class="loader__label">${escapeHtml(label)}</div>
      <div class="loader__bar" aria-hidden="true">
        <div class="loader__bar-fill" style="width:${pct}%"></div>
      </div>
      <div class="loader__counter">${escapeHtml(counter)}</div>
    </div>
  `;
}

function stubBlock(reason: string): string {
  return /* html */ `
    <div class="loader loader--stub" role="status">
      <div class="loader__label">Welcome to Macintosh.</div>
      <p class="loader__note">
        Stub: emulator integration in progress.
      </p>
      <p class="loader__note loader__note--small">
        ${escapeHtml(reason)}
      </p>
    </div>
  `;
}

function errorBlock(message: string): string {
  return /* html */ `
    <div class="loader loader--error" role="alert">
      <div class="loader__label">Sorry, a system error occurred.</div>
      <p class="loader__note loader__note--small">${escapeHtml(message)}</p>
    </div>
  `;
}

// ── Helpers ──────────────────────────────────────────────────────────

function formatBytes(n: number): string {
  if (n <= 0) return "";
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / 1024 / 1024).toFixed(1)} MB`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
