/**
 * shared-poller.ts — implements the host side of Reader's URL bar (issue #14).
 *
 * Architecture:
 *   1. The Mac-side Reader writes a URL request to :Unix:__url-request.txt
 *      (which is /Shared/__url-request.txt in the Emscripten FS).
 *      Format: "<requestId>\n<url>\n" (ASCII/MacRoman).
 *
 *   2. This module polls the request file via the worker's `poll_url_request`
 *      message every POLL_INTERVAL_MS. When a new requestId arrives it:
 *        a. Cancels any in-flight fetch via AbortController.
 *        b. Resolves the URL shortcut (wiki:, gh:, library/, https://).
 *        c. fetch()es the HTML on the main thread (the worker can't do this
 *           because Atomics.wait starves its microtask queue).
 *        d. Strips the HTML to body-only text content the Reader parser can
 *           handle (<=MAX_HTML_BYTES bytes after trimming).
 *        e. Transcodes UTF-8 → MacRoman.
 *        f. Writes the result via `url_result_write` to
 *           /Shared/__url-result-<requestId>.html.
 *
 *   3. Reader polls :Unix:__url-result-<id>.html and renders it when found.
 *
 * Runs entirely on the main thread — no Worker-side async needed.
 */

const POLL_INTERVAL_MS = 2000;

/** Cap the result HTML at this many MacRoman bytes to fit Reader's 16 KB buffer. */
const MAX_HTML_BYTES = 12_000;

export interface SharedPollerConfig {
  worker: Worker;
}

export function startSharedPoller(config: SharedPollerConfig): () => void {
  const { worker } = config;
  let lastRequestId: string | null = null;
  let activeAbort: AbortController | null = null;
  let intervalId: ReturnType<typeof setInterval> | null = null;
  let stopped = false;

  function handleMessage(ev: MessageEvent) {
    const data = ev.data;
    if (data?.type !== "url_request_data") return;
    const bytes: Uint8Array | null = data.bytes ?? null;
    if (!bytes || bytes.length === 0) return;

    // Parse "requestId\nurl\n"
    const raw = new TextDecoder("utf-8", { fatal: false }).decode(bytes);
    const nl = raw.indexOf("\n");
    if (nl < 0) return;
    const requestId = raw.slice(0, nl).trim();
    const url = raw.slice(nl + 1).trim();
    if (!requestId || !url) return;
    if (requestId === lastRequestId) return; // already handled

    lastRequestId = requestId;

    // Cancel any previous in-flight fetch.
    if (activeAbort) {
      activeAbort.abort();
      activeAbort = null;
    }

    const abort = new AbortController();
    activeAbort = abort;
    void fetchAndDeliver(url, requestId, abort.signal, worker).finally(() => {
      if (activeAbort === abort) activeAbort = null;
    });
  }

  worker.addEventListener("message", handleMessage);
  intervalId = setInterval(() => {
    if (!stopped) worker.postMessage({ type: "poll_url_request" });
  }, POLL_INTERVAL_MS);

  return () => {
    stopped = true;
    if (intervalId !== null) clearInterval(intervalId);
    worker.removeEventListener("message", handleMessage);
    if (activeAbort) { activeAbort.abort(); activeAbort = null; }
  };
}

// ── URL resolution ──────────────────────────────────────────────────────────

/**
 * Resolve a URL shortcut to a fetch URL plus a display title.
 *   wiki:Article Name      → Wikipedia REST API (CORS-permissive)
 *   gh:user/repo/path/file → raw.githubusercontent.com (CORS-permissive)
 *   library/file.html      → /library/file.html (same-origin, no CORS)
 *   https://...            → direct fetch (may fail due to CORS)
 *
 * Returns null for unrecognised schemes (error HTML is generated by caller).
 */
function resolveUrl(raw: string): { fetchUrl: string; display: string } | null {
  const s = raw.trim();

  if (s.startsWith("wiki:")) {
    const article = s.slice(5).trim().replace(/ /g, "_");
    return {
      fetchUrl: `https://en.wikipedia.org/api/rest_v1/page/html/${encodeURIComponent(article)}`,
      display: `Wikipedia: ${article}`,
    };
  }

  if (s.startsWith("gh:")) {
    const rest = s.slice(3).trim();
    return {
      fetchUrl: `https://raw.githubusercontent.com/${rest}`,
      display: `GitHub: ${rest}`,
    };
  }

  if (s.startsWith("library/")) {
    return {
      fetchUrl: `/${s}`,
      display: s,
    };
  }

  if (s.startsWith("https://") || s.startsWith("http://")) {
    return { fetchUrl: s, display: s };
  }

  return null;
}

// ── Fetch + transform ───────────────────────────────────────────────────────

async function fetchAndDeliver(
  rawUrl: string,
  requestId: string,
  signal: AbortSignal,
  worker: Worker,
): Promise<void> {
  const resultPath = `/Shared/__url-result-${requestId}.html`;

  const resolved = resolveUrl(rawUrl);
  if (!resolved) {
    const html = buildErrorHtml(`Unsupported URL scheme: <b>${escapeHtml(rawUrl)}</b>`
      + `<p>Supported: <i>wiki:Article</i>, <i>gh:user/repo/path</i>, `
      + `<i>library/file.html</i>, <i>https://...</i></p>`);
    deliver(worker, resultPath, html);
    return;
  }

  let responseText: string;
  try {
    const resp = await fetch(resolved.fetchUrl, { signal });
    if (!resp.ok) {
      throw new Error(`HTTP ${resp.status} ${resp.statusText}`);
    }
    responseText = await resp.text();
  } catch (err: unknown) {
    if (signal.aborted) return; // superseded by newer request
    const msg = err instanceof Error ? err.message : String(err);
    const isCors = msg.toLowerCase().includes("failed to fetch");
    const html = buildErrorHtml(
      `<b>Could not fetch:</b> ${escapeHtml(resolved.display)}`
        + (isCors
          ? `<p>CORS policy blocked the request. Try <i>wiki:</i> or <i>gh:</i> shortcuts instead.</p>`
          : `<p>${escapeHtml(msg)}</p>`),
    );
    deliver(worker, resultPath, html);
    return;
  }

  if (signal.aborted) return;

  const simplified = stripToReadableHtml(responseText, resolved.display);
  deliver(worker, resultPath, simplified);
}

function deliver(worker: Worker, path: string, html: string): void {
  const bytes = toMacRoman(html);
  worker.postMessage({ type: "url_result_write", path, bytes });
}

// ── HTML simplification ─────────────────────────────────────────────────────

/**
 * Strip a full HTML page down to the subset Reader's parser can handle:
 *   - Remove <script>, <style>, <head>
 *   - Keep <h1>-<h3>, <p>, <br>, <b>/<strong>, <i>/<em>, <ul>/<li>, <a href>, <pre>
 *   - Truncate at MAX_HTML_BYTES, appending a marker
 */
function stripToReadableHtml(raw: string, title: string): string {
  // 1. Remove script / style / head sections entirely (including content).
  let h = raw;
  h = h.replace(/<script[\s\S]*?<\/script>/gi, "");
  h = h.replace(/<style[\s\S]*?<\/style>/gi, "");
  h = h.replace(/<head[\s\S]*?<\/head>/gi, "");

  // 2. Pull out the <body> content if present.
  const bodyMatch = h.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
  if (bodyMatch) h = bodyMatch[1];

  // 3. Strip all tag attributes except <a href="...">.
  h = h.replace(/<a\s+[^>]*href\s*=\s*["']([^"']*?)["'][^>]*>/gi, '<a href="$1">');
  h = h.replace(/<([a-zA-Z0-9]+)(\s+[^>]*)?>/g, (match, tag: string) => {
    const t = tag.toLowerCase();
    const keepAttr = ["h1","h2","h3","p","b","strong","i","em","ul","ol","li","br","pre","a"].includes(t);
    if (keepAttr) return `<${t}>`; // already stripped attr above for <a>
    if (t === "a") return match; // keep the href-only form from above
    return `<${t}>`;
  });

  // 4. Flatten whitespace in non-pre sections (crude but serviceable).
  h = h.replace(/\n{3,}/g, "\n\n");

  // 5. Add a title heading.
  h = `<h2>${escapeHtml(title)}</h2>\n` + h;

  // 6. Truncate to MAX_HTML_BYTES and add a marker if needed.
  const enc = new TextEncoder();
  const bytes = enc.encode(h);
  if (bytes.length > MAX_HTML_BYTES) {
    // Truncate and add a visible marker.
    const truncated = new TextDecoder().decode(bytes.subarray(0, MAX_HTML_BYTES - 60));
    // Trim to last complete tag boundary (crude: find last ">")
    const lastTag = truncated.lastIndexOf(">");
    const safe = lastTag > 0 ? truncated.slice(0, lastTag + 1) : truncated;
    h = safe + "\n<p><i>[Content truncated — page too large for Reader]</i></p>";
  }

  return h;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;")
          .replace(/</g, "&lt;")
          .replace(/>/g, "&gt;")
          .replace(/"/g, "&quot;");
}

function buildErrorHtml(body: string): string {
  return `<h2>Fetch Error</h2>\n<p>${body}</p>`;
}

// ── MacRoman encoder ────────────────────────────────────────────────────────

/**
 * Encode a JavaScript string to MacRoman bytes (Uint8Array).
 *
 * Steps:
 *   1. Normalise common Unicode punctuation to ASCII equivalents.
 *   2. Map each remaining character via the MacRoman reverse table.
 *   3. Characters without a MacRoman equivalent become '?' (0x3F).
 *
 * The Mac ROM renders these bytes via the MacRoman system font — the
 * output should be legible for Western European content.
 */
export function toMacRoman(s: string): Uint8Array {
  // Step 1: normalise common Unicode smart-punctuation → ASCII.
  const n = s
    .replace(/\u2018|\u2019|\u0060/g, "'")   // left/right single quote, backtick
    .replace(/\u201C|\u201D/g, '"')           // left/right double quote
    .replace(/\u2013|\u2014/g, "-")           // en-dash / em-dash
    .replace(/\u2026/g, "...")                // ellipsis
    .replace(/\u2022/g, "*")                  // bullet
    .replace(/\u00A0/g, " ")                  // non-breaking space
    .replace(/\u2010|\u2011/g, "-")           // hyphen variants
    .replace(/\u00AD/g, "-")                  // soft hyphen
    .replace(/\uFEFF/g, "");                  // BOM / zero-width no-break space

  const buf = new Uint8Array(n.length * 3); // worst-case (longer due to "...")
  let out = 0;
  for (let i = 0; i < n.length; i++) {
    const cp = n.codePointAt(i)!;
    if (cp > 0xFFFF) i++; // skip surrogate pair second half (already normalised)
    if (cp < 0x80) {
      buf[out++] = cp;
    } else {
      const mac = UNICODE_TO_MACR.get(cp);
      buf[out++] = mac !== undefined ? mac : 0x3F; // '?'
    }
  }
  return buf.subarray(0, out);
}

/**
 * MacRoman character set: reverse table (Unicode codepoint → MacRoman byte).
 * Only the 0x80-0xFF range differs from ASCII; 0x00-0x7F map 1:1.
 *
 * Source: IANA charset registry "macintosh", cross-checked with
 * https://en.wikipedia.org/wiki/Mac_OS_Roman
 */
const MACR: [number, number][] = [
  // MacRoman byte, Unicode codepoint
  [0x80, 0x00C4], [0x81, 0x00C5], [0x82, 0x00C7], [0x83, 0x00C9],
  [0x84, 0x00D1], [0x85, 0x00D6], [0x86, 0x00DC], [0x87, 0x00E1],
  [0x88, 0x00E0], [0x89, 0x00E2], [0x8A, 0x00E4], [0x8B, 0x00E5],
  [0x8C, 0x00E7], [0x8D, 0x00E9], [0x8E, 0x00E8], [0x8F, 0x00EA],
  [0x90, 0x00EB], [0x91, 0x00ED], [0x92, 0x00EC], [0x93, 0x00EE],
  [0x94, 0x00EF], [0x95, 0x00F1], [0x96, 0x00F3], [0x97, 0x00F2],
  [0x98, 0x00F4], [0x99, 0x00F6], [0x9A, 0x00FA], [0x9B, 0x00F9],
  [0x9C, 0x00FB], [0x9D, 0x00FC], [0x9E, 0x2020], [0x9F, 0x00B0],
  [0xA0, 0x00A2], [0xA1, 0x00A3], [0xA2, 0x00A7], [0xA3, 0x2022],
  [0xA4, 0x00B6], [0xA5, 0x00DF], [0xA6, 0x00AE], [0xA7, 0x00A9],
  [0xA8, 0x2122], [0xA9, 0x00B4], [0xAA, 0x00A8], [0xAB, 0x2260],
  [0xAC, 0x00C6], [0xAD, 0x00D8], [0xAE, 0x221E], [0xAF, 0x00B1],
  [0xB0, 0x2264], [0xB1, 0x2265], [0xB2, 0x00A5], [0xB3, 0x00B5],
  [0xB4, 0x2202], [0xB5, 0x2211], [0xB6, 0x220F], [0xB7, 0x03C0],
  [0xB8, 0x222B], [0xB9, 0x00AA], [0xBA, 0x00BA], [0xBB, 0x03A9],
  [0xBC, 0x00E6], [0xBD, 0x00F8], [0xBE, 0x00BF], [0xBF, 0x00A1],
  [0xC0, 0x00AC], [0xC1, 0x221A], [0xC2, 0x0192], [0xC3, 0x2248],
  [0xC4, 0x2206], [0xC5, 0x00AB], [0xC6, 0x00BB], [0xC7, 0x2026],
  [0xC8, 0x00A0], [0xC9, 0x00C0], [0xCA, 0x00C3], [0xCB, 0x00D5],
  [0xCC, 0x0152], [0xCD, 0x0153], [0xCE, 0x2013], [0xCF, 0x2014],
  [0xD0, 0x201C], [0xD1, 0x201D], [0xD2, 0x2018], [0xD3, 0x2019],
  [0xD4, 0x00F7], [0xD5, 0x25CA], [0xD6, 0x00FF], [0xD7, 0x0178],
  [0xD8, 0x2044], [0xD9, 0x20AC], [0xDA, 0x2039], [0xDB, 0x203A],
  [0xDC, 0xFB01], [0xDD, 0xFB02], [0xDE, 0x2021], [0xDF, 0x00B7],
  [0xE0, 0x201A], [0xE1, 0x201E], [0xE2, 0x2030], [0xE3, 0x00C2],
  [0xE4, 0x00CA], [0xE5, 0x00C1], [0xE6, 0x00CB], [0xE7, 0x00C8],
  [0xE8, 0x00CD], [0xE9, 0x00CE], [0xEA, 0x00CF], [0xEB, 0x00CC],
  [0xEC, 0x00D3], [0xED, 0x00D4], [0xEF, 0x00D2], [0xF0, 0x00DA],
  [0xF1, 0x00DB], [0xF2, 0x00D9], [0xF3, 0x0131], [0xF4, 0x02C6],
  [0xF5, 0x02DC], [0xF6, 0x00AF], [0xF7, 0x02D8], [0xF8, 0x02D9],
  [0xF9, 0x02DA], [0xFA, 0x00B8], [0xFB, 0x02DD], [0xFC, 0x02DB],
  [0xFD, 0x02C7],
];
const UNICODE_TO_MACR = new Map<number, number>(MACR.map(([mac, uni]) => [uni, mac]));
